[tools]
ruby = "4.0.6"
"aqua:jdx/hk" = "1.53.0"
"aqua:apple/pkl" = "0.31.1"
"aqua:rhysd/actionlint" = "1.7.12"
"aqua:zizmorcore/zizmor" = "1.24.1"

[settings]
disable_backends = ["asdf"]

[settings.ruby]
compile = false

[tasks.pre-commit]
run = "hk run pre-commit"

[tasks.setup]
run = "bin/setup"
