# frozen_string_literal: true

target :lib do
  signature "sig", "sig-stub"

  check "lib"
  # Generated by buf; typed by hand in sig/buf/validate/validate_pb.rbs instead.
  ignore "lib/buf/**/*.rb"
end
