# frozen_string_literal: true

require "set"

module Protovalidate
  # Validates messages against the buf.validate rules of their schema.
  #
  # A validator owns a native engine that compiles the rules of each message
  # type once and caches them, so reuse one instance rather than creating one
  # per validation. Instances may be shared between threads; Ractors are not
  # supported.
  #
  # The rules of a message type are compiled the first time it is validated,
  # and concurrent validations wait while that happens. {#register} moves the
  # compilation to a time of your choosing, such as application boot.
  class Validator
    # @param descriptor_pool [Google::Protobuf::DescriptorPool] pool the
    #   validated messages' schema files and their imports are looked up in
    def initialize(descriptor_pool: Google::Protobuf::DescriptorPool.generated_pool)
      @descriptor_pool = descriptor_pool
      @engine = Native::Engine.new
      @registered_files = Set.new
      types = {} #: Hash[message_class, String]
      @types = types.compare_by_identity.freeze
      @registration = Mutex.new
    end

    # Compiles the rules of message classes ahead of their first validation.
    #
    # Classes not registered here are still compiled on first use, so this is
    # an optimization, not a requirement.
    #
    # @param message_classes [Array<Class>] message classes generated by google-protobuf
    # @return [void]
    # @raise [CompilationError] when the rules of a message type cannot be compiled
    # @raise [ArgumentError] when an import of a message's file is missing from the pool
    # @raise [TypeError] when a class is not a Protobuf message class
    def register(*message_classes)
      message_classes.each { |klass| type_name_of(klass) }
      nil
    end

    # Validates a message, raising when it is invalid.
    #
    # @param message [Google::Protobuf::MessageExts]
    # @param fail_fast [Boolean] stop at the first violation
    # @return [void]
    # @raise [ValidationError] when the message violates its rules; its
    #   violations equal what {#collect_violations} returns
    # @raise [CompilationError] when the rules of the message type cannot be compiled
    # @raise [EvaluationError] when a rule fails during evaluation
    # @raise [TypeError] when `message` is not a Protobuf message
    def validate(message, fail_fast: false)
      violations = collect_violations(message, fail_fast:)
      return if violations.empty?

      raise ValidationError.new("invalid #{message.class.descriptor.name}", violations)
    end

    # Validates a message and returns its violations instead of raising.
    #
    # @param message [Google::Protobuf::MessageExts]
    # @param fail_fast [Boolean] stop at the first violation
    # @return [Array<Violation>] empty when the message is valid
    # @raise [CompilationError] when the rules of the message type cannot be compiled
    # @raise [EvaluationError] when a rule fails during evaluation
    # @raise [TypeError] when `message` is not a Protobuf message
    def collect_violations(message, fail_fast: false)
      type_name = type_name_of(message.class)
      serialized = @engine.validate(type_name, message.class.encode(message), fail_fast)
      return [] if serialized.nil?

      Buf::Validate::Violations.decode(serialized).violations.map do |proto|
        Violation.new(proto, message)
      end
    end

    # The full name of a message class's type, registering and compiling it on
    # first sight. Registered classes resolve with one lookup and no lock.
    private def type_name_of(klass)
      @types[klass] || register_class(klass)
    end

    # @types is replaced with a frozen copy rather than mutated, so a reader
    # outside the lock never observes a Hash being written to.
    private def register_class(klass)
      descriptor = descriptor_of(klass)
      @registration.synchronize do
        @types[klass] || begin
          register_file(descriptor.file_descriptor)
          name = descriptor.name.freeze
          @engine.compile(name)
          types = @types.dup
          types[klass] = name
          @types = types.freeze
          name
        end
      end
    end

    private def descriptor_of(klass)
      unless klass.is_a?(Google::Protobuf::MessageExts::ClassMethods)
        raise TypeError, "expected a Google::Protobuf message class, got #{klass.inspect}"
      end

      klass.descriptor
    end

    # The engine resolves imports eagerly, so they are added before the importer.
    private def register_file(file)
      return if @registered_files.include?(file.name)

      proto = file.to_proto
      proto.dependency.each do |name|
        dependency = @descriptor_pool.lookup(name)
        unless dependency.is_a?(Google::Protobuf::FileDescriptor)
          raise ArgumentError, "#{file.name} imports #{name}, which is not in the descriptor pool"
        end

        register_file(dependency)
      end
      @engine.add_file(Google::Protobuf::FileDescriptorProto.encode(proto))
      @registered_files << file.name
    end
  end
end
